project:
  type: website
  output-dir: docs

website:
  title: "Jeanie's Personal Site"
  favicon: img/project.jpg
  navbar:
    logo: img/nav.jpg
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: DataVis.qmd
        text: Data Visualization
      - href: Reflection.qmd
        text: Reflection

format:
  html:
    theme: darkly
    css: styles.css
    toc: true
    toc-depth: 3
    toc-location: left

editor: visual
